### ISSUE TITLE
Show user who have permission via group too

### ISSUE THREAD

**Issue by iaincrawf** [linn/authorisation#47]
All of IT have this permission via the group but can't see it without going into the group - could show everyone who has it for each group too?

Could maybe also come up with a way of highlighting people who have the permission normally and via a groups

![image](https://user-images.githubusercontent.com/51612225/136203563-1a1157ee-ee39-42a7-8d96-7fd1645a66ee.png)

**Comment by RossStewart** [comment]
This is now shown on the permissions menu, users show whether they have a permission assigned via group or if it is an individual permission.
