### ISSUE TITLE
can't go directly to /authorisation/groups

### ISSUE THREAD

**Issue by iaincrawf** [linn/authorisation#52]
can't go directly to https://app.linn.co.uk/authorisation/groups or refresh the page, some front end routing this must be missing

**Comment by RossStewart** [comment]
![image](https://user-images.githubusercontent.com/1224936/140525477-fc9bb30d-a226-48ce-bc00-a8e4a96f054e.png)


Just a note to say that I'm able to go directly to this on this localhost set up but not on app?
